import { NextResponse } from "next/server";
import { z } from "zod";
import { getAuthenticatedUser } from "@/lib/supabase/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { isPossibleDuplicate,type ContributionEvent } from "@/lib/recap";
import { generateMonthlyRecap } from "@/lib/server/recaps";
const createSchema=z.object({amount:z.number().positive().max(10_000_000),occurredOn:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),kind:z.enum(["contribution","withdrawal"]).default("contribution"),allowDuplicate:z.boolean().default(false)});
export async function GET(){const user=await getAuthenticatedUser(),admin=createSupabaseAdminClient();if(!user)return NextResponse.json({reason:"Sign in to view contributions."},{status:401});if(!admin)return NextResponse.json({reason:"Contribution storage is not configured."},{status:503});const {data,error}=await admin.from("contribution_events").select("id,account_id,provider_transaction_id,occurred_on,amount,currency,direction,source,status,confidence,user_corrected,created_at").eq("user_id",user.id).neq("status","deleted").order("occurred_on",{ascending:false});if(error)return NextResponse.json({reason:"Contributions are unavailable."},{status:500});return NextResponse.json({contributions:data},{headers:{"Cache-Control":"private, no-store"}})}
export async function POST(request:Request){const user=await getAuthenticatedUser(),admin=createSupabaseAdminClient();if(!user)return NextResponse.json({reason:"Sign in to add a contribution."},{status:401});if(!admin)return NextResponse.json({reason:"Contribution storage is not configured."},{status:503});const parsed=createSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({reason:"Enter a valid amount and date."},{status:400});const {data:rows}=await admin.from("contribution_events").select("id,occurred_on,amount,currency,direction,status,source").eq("user_id",user.id).neq("status","deleted");const events:ContributionEvent[]=(rows??[]).map(row=>({id:String(row.id),occurredOn:String(row.occurred_on),amount:Number(row.amount),currency:"USD",kind:row.direction,status:row.status,source:row.source}));if(!parsed.data.allowDuplicate&&isPossibleDuplicate(events,{occurredOn:parsed.data.occurredOn,amount:parsed.data.amount}))return NextResponse.json({reason:"This may duplicate activity within two days.",duplicate:true},{status:409});const {data,error}=await admin.from("contribution_events").insert({user_id:user.id,occurred_on:parsed.data.occurredOn,amount:parsed.data.amount,currency:"USD",direction:parsed.data.kind,source:"manual",status:"confirmed",confidence:1,user_corrected:true,classification_reason:"Entered by user"}).select().single();if(error)return NextResponse.json({reason:"Contribution could not be saved."},{status:500});const {data:preference}=await admin.from("recap_preferences").select("history_eligible_since").eq("user_id",user.id).maybeSingle();if(!preference?.history_eligible_since||String(preference.history_eligible_since)>parsed.data.occurredOn)await admin.from("recap_preferences").upsert({user_id:user.id,history_eligible_since:parsed.data.occurredOn,updated_at:new Date().toISOString()},{onConflict:"user_id"});const recap=await generateMonthlyRecap(user.id,parsed.data.occurredOn.slice(0,7));return NextResponse.json({contribution:data,recap},{status:201})}
