import { NextResponse } from "next/server";
import { z } from "zod";
import { getAuthenticatedUser } from "@/lib/supabase/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { generateMonthlyRecap } from "@/lib/server/recaps";
import { isPossibleDuplicate,type ContributionEvent } from "@/lib/recap";
const patchSchema=z.object({status:z.enum(["confirmed","excluded"]).optional(),amount:z.number().positive().max(10_000_000).optional(),occurredOn:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(),allowDuplicate:z.boolean().optional()}).refine(value=>Object.keys(value).some(key=>key!=="allowDuplicate"));
export async function PATCH(request:Request,{params}:{params:Promise<{id:string}>}){const user=await getAuthenticatedUser(),admin=createSupabaseAdminClient();if(!user)return NextResponse.json({reason:"Sign in to update activity."},{status:401});if(!admin)return NextResponse.json({reason:"Contribution storage is not configured."},{status:503});const {id}=await params;const parsed=patchSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({reason:"Choose a valid correction."},{status:400});const {data:existing}=await admin.from("contribution_events").select("source,occurred_on,amount").eq("id",id).eq("user_id",user.id).maybeSingle();if(!existing)return NextResponse.json({reason:"Activity not found."},{status:404});if(existing.source!=="manual"&&(parsed.data.amount!==undefined||parsed.data.occurredOn!==undefined))return NextResponse.json({reason:"Linked amounts and dates cannot be edited. Exclude the item and add a manual correction."},{status:409});if(existing.source==="manual"&&!parsed.data.allowDuplicate&&(parsed.data.amount!==undefined||parsed.data.occurredOn)){const {data:rows}=await admin.from("contribution_events").select("id,occurred_on,amount,direction,status,source").eq("user_id",user.id).neq("status","deleted");const events:ContributionEvent[]=(rows??[]).map(row=>({id:String(row.id),occurredOn:String(row.occurred_on),amount:Number(row.amount),currency:"USD",kind:row.direction,status:row.status,source:row.source}));if(isPossibleDuplicate(events,{occurredOn:parsed.data.occurredOn||String(existing.occurred_on),amount:parsed.data.amount??Number(existing.amount)},id))return NextResponse.json({reason:"This may duplicate activity within two days.",duplicate:true},{status:409})}const changes={...(parsed.data.status&&{status:parsed.data.status}),...(parsed.data.amount!==undefined&&{amount:parsed.data.amount}),...(parsed.data.occurredOn&&{occurred_on:parsed.data.occurredOn}),user_corrected:true,updated_at:new Date().toISOString()};const {data,error}=await admin.from("contribution_events").update(changes).eq("id",id).eq("user_id",user.id).select().single();if(error)return NextResponse.json({reason:"Activity could not be updated."},{status:500});const oldPeriod=String(existing.occurred_on).slice(0,7),newPeriod=(parsed.data.occurredOn||existing.occurred_on).slice(0,7);if(oldPeriod!==newPeriod)await generateMonthlyRecap(user.id,oldPeriod);const recap=await generateMonthlyRecap(user.id,newPeriod);return NextResponse.json({contribution:data,recap})}
export async function DELETE(_request:Request,{params}:{params:Promise<{id:string}>}){const user=await getAuthenticatedUser(),admin=createSupabaseAdminClient();if(!user)return NextResponse.json({reason:"Sign in to remove activity."},{status:401});if(!admin)return NextResponse.json({reason:"Contribution storage is not configured."},{status:503});const {id}=await params;const {data:existing}=await admin.from("contribution_events").select("occurred_on").eq("id",id).eq("user_id",user.id).maybeSingle();if(!existing)return NextResponse.json({reason:"Activity not found."},{status:404});const {error}=await admin.from("contribution_events").update({status:"deleted",deleted_at:new Date().toISOString(),user_corrected:true,updated_at:new Date().toISOString()}).eq("id",id).eq("user_id",user.id);if(error)return NextResponse.json({reason:"Activity could not be removed."},{status:500});const recap=await generateMonthlyRecap(user.id,String(existing.occurred_on).slice(0,7));return NextResponse.json({deleted:true,recap})}
