import { after,NextResponse } from "next/server";
import { z } from "zod";
import { getAuthenticatedUser } from "@/lib/supabase/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { encryptSecret } from "@/lib/crypto";
import { exchangePublicToken } from "@/lib/providers/plaid";
import { syncPlaidConnection } from "@/lib/server/plaid-sync";
const schema=z.object({publicToken:z.string().min(10).max(4096),institutionName:z.string().trim().min(1).max(120)});
export async function POST(request:Request){const user=await getAuthenticatedUser(),admin=createSupabaseAdminClient();if(!user)return NextResponse.json({reason:"Sign in before connecting a portfolio."},{status:401});if(!admin)return NextResponse.json({reason:"Secure portfolio storage is not configured."},{status:503});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({reason:"The account-link response was invalid."},{status:400});try{const exchanged=await exchangePublicToken(parsed.data.publicToken);const {data:owner}=await admin.from("portfolio_connections").select("user_id").eq("provider_item_id",exchanged.itemId).maybeSingle();if(owner&&owner.user_id!==user.id)return NextResponse.json({reason:"This connection already belongs to another account."},{status:409});const {data,error}=await admin.from("portfolio_connections").upsert({user_id:user.id,source:"plaid",institution_name:parsed.data.institutionName,encrypted_access_token:encryptSecret(exchanged.accessToken),provider_item_id:exchanged.itemId,status:"syncing",updated_at:new Date().toISOString()},{onConflict:"provider_item_id"}).select("id,status").single();if(error)throw error;after(async()=>{await syncPlaidConnection(data.id).catch(()=>undefined)});return NextResponse.json({connection:{id:data.id,status:"syncing"},message:"Building your history. Initial investment activity can take a minute or two."},{status:202})}catch{return NextResponse.json({reason:"The brokerage connection could not be completed."},{status:502})}}
