import "server-only";
import { env,integrations } from "@/lib/env";
import { validStripeSignature } from "@/lib/webhook-signature";
async function request(path:string,params:URLSearchParams,method:"POST"|"DELETE"="POST"){if(!integrations.stripe)throw new Error("Billing is not configured.");const response=await fetch(`https://api.stripe.com/v1/${path}`,{method,headers:{authorization:`Bearer ${env.STRIPE_SECRET_KEY}`,"content-type":"application/x-www-form-urlencoded"},body:params,cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body?.error?.message||"Billing provider rejected the request.");return body}
export async function createCheckout(userId:string,email:string|undefined,price:"monthly"|"annual"){const priceId=price==="annual"?env.STRIPE_ANNUAL_PRICE_ID:env.STRIPE_MONTHLY_PRICE_ID;const origin=env.APP_URL||"http://localhost:3001";const params=new URLSearchParams({mode:"subscription",success_url:`${origin}/recap?checkout=success`,cancel_url:`${origin}/recap?checkout=cancelled`,client_reference_id:userId,"line_items[0][price]":priceId!,"line_items[0][quantity]":"1","subscription_data[trial_period_days]":"14","subscription_data[metadata][user_id]":userId,"metadata[user_id]":userId,allow_promotion_codes:"true"});if(email)params.set("customer_email",email);return request("checkout/sessions",params)}
export async function createPortal(customerId:string){const origin=env.APP_URL||"http://localhost:3001";return request("billing_portal/sessions",new URLSearchParams({customer:customerId,return_url:`${origin}/settings`}))}
export async function cancelSubscription(subscriptionId:string){return request(`subscriptions/${encodeURIComponent(subscriptionId)}`,new URLSearchParams(),"DELETE")}
export async function deleteStripeCustomer(customerId:string){return request(`customers/${encodeURIComponent(customerId)}`,new URLSearchParams(),"DELETE")}
export function verifyStripeWebhook(raw:string,header:string|null,now=Math.floor(Date.now()/1000)){return validStripeSignature(raw,header,env.STRIPE_WEBHOOK_SECRET,now)}
