import { NextResponse } from "next/server";
import { z } from "zod";
import { getAuthenticatedUser } from "@/lib/supabase/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { hasProEntitlement } from "@/lib/billing";
const schema=z.object({emailOptIn:z.boolean().optional(),timezone:z.string().min(1).max(80).optional(),cohortOptIn:z.boolean().optional(),latestSeenPeriod:z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/).optional(),customMilestones:z.array(z.number().positive().max(100_000_000)).max(10).optional()}).refine(value=>Object.keys(value).length>0);
function configuredTimezone(value:string){try{new Intl.DateTimeFormat("en-US",{timeZone:value}).format();return true}catch{return false}}
export async function GET(){const user=await getAuthenticatedUser(),admin=createSupabaseAdminClient();if(!user)return NextResponse.json({reason:"Sign in to view recap preferences."},{status:401});if(!admin)return NextResponse.json({reason:"Recap preferences are not configured."},{status:503});const {data}=await admin.from("recap_preferences").select("email_opt_in,timezone,cohort_opt_in,campus_domain,campus_verified_at,latest_seen_period,custom_milestones").eq("user_id",user.id).maybeSingle();return NextResponse.json({preferences:data??{email_opt_in:false,timezone:"America/Chicago",cohort_opt_in:false,custom_milestones:[]}})}
export async function PUT(request:Request){const user=await getAuthenticatedUser(),admin=createSupabaseAdminClient();if(!user)return NextResponse.json({reason:"Sign in to save recap preferences."},{status:401});if(!admin)return NextResponse.json({reason:"Recap preferences are not configured."},{status:503});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success||parsed.data.timezone&&!configuredTimezone(parsed.data.timezone))return NextResponse.json({reason:"Choose valid recap preferences."},{status:400});if(parsed.data.customMilestones!==undefined){const {data:entitlement}=await admin.from("subscription_entitlements").select("status,current_period_end").eq("user_id",user.id).maybeSingle();if(!hasProEntitlement(entitlement?.status,entitlement?.current_period_end))return NextResponse.json({reason:"Custom milestones are available with Pro."},{status:403})}const changes={user_id:user.id,...(parsed.data.emailOptIn!==undefined&&{email_opt_in:parsed.data.emailOptIn}),...(parsed.data.timezone&&{timezone:parsed.data.timezone}),...(parsed.data.cohortOptIn!==undefined&&{cohort_opt_in:parsed.data.cohortOptIn}),...(parsed.data.latestSeenPeriod&&{latest_seen_period:parsed.data.latestSeenPeriod}),...(parsed.data.customMilestones&&{custom_milestones:[...new Set(parsed.data.customMilestones)].sort((a,b)=>a-b)}),updated_at:new Date().toISOString()};const {data,error}=await admin.from("recap_preferences").upsert(changes,{onConflict:"user_id"}).select().single();if(error)return NextResponse.json({reason:"Preferences could not be saved."},{status:500});return NextResponse.json({preferences:data})}
