"use client";
import Link from "next/link";
import { Search, Bookmark, ArrowUpRight, ChevronDown } from "lucide-react";
import { useState } from "react";
import { useDemo } from "./demo-provider";
const research=[
 {id:"vti",symbol:"VTI",title:"One fund. A broad slice of U.S. stocks.",type:"Funds",summary:"VTI is a U.S. stock-market fund. A broad fund can spread company-specific risk, while still depending on the U.S. market as a whole.",lesson:"spread-your-risk",source:"https://investor.vanguard.com/investment-products/etfs/profile/vti",sourceLabel:"Vanguard fund overview"},
 {id:"vxus",symbol:"VXUS",title:"What’s beyond the U.S. market?",type:"Funds",summary:"VXUS holds stocks outside the U.S., across developed and emerging markets. Currency changes and regional events add different risks; international stocks can fall too.",lesson:"spread-your-risk",source:"https://investor.vanguard.com/investment-products/etfs/profile/vxus",sourceLabel:"Vanguard fund overview"},
 {id:"aapl",symbol:"AAPL",title:"Read Apple’s business, not just its stock price.",type:"Stocks",summary:"For any company, compare revenue, profit and cash flow over time. Then look at debt, risks and management’s explanation. A price move alone does not tell you why it happened.",lesson:"read-earnings",source:"https://www.investor.gov/introduction-investing/investing-basics/investment-products/stocks",sourceLabel:"Investor.gov · Stock research basics"},
 {id:"bnd",symbol:"BND",title:"Bonds have a different job. And their own risks.",type:"Bonds",summary:"BND holds bonds rather than company shares. Bond funds can change in price as interest rates move, and their holdings can have credit risk. They are not a cash guarantee.",lesson:"what-you-own",source:"https://investor.vanguard.com/investment-products/etfs/profile/bnd",sourceLabel:"Vanguard fund overview"},
 {id:"ixus",symbol:"IXUS",title:"Two international funds may own similar things.",type:"Funds",summary:"IXUS offers a broad basket of non-U.S. stocks. Compare its holdings with other international funds before assuming another ticker adds new exposure.",lesson:"spread-your-risk",source:"https://www.ishares.com/us/products/244048/ishares-core-msci-total-international-stock-etf",sourceLabel:"iShares fund overview"}
];
export function DiscoverSearch({initialQuery=""}:{initialQuery?:string}){
 const [query,setQuery]=useState(initialQuery);const [filter,setFilter]=useState("All");const {preferences,update,announce}=useDemo();const shown=research.filter(item=>(filter==="All"||(filter==="Saved"?preferences.saved.includes(item.id):item.type===filter))&&`${item.symbol} ${item.title} ${item.summary} ${item.type} ${item.sourceLabel}`.toLowerCase().includes(query.trim().toLowerCase()));
 function save(id:string){const saved=preferences.saved.includes(id);update({saved:saved?preferences.saved.filter(x=>x!==id):[...preferences.saved,id]});announce(saved?"Removed from saved research.":"Saved. Find it in the Saved tab.");}
 return <div className="workspace"><label className="searchbox"><Search size={18}/><span className="sr-only">Search investments and research</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Try a ticker, fund or investing question"/>{query&&<button className="search-clear" aria-label="Clear search" onClick={()=>setQuery("")}>×</button>}</label><div className="demo-toolbar"><div className="demo-tabs" role="group" aria-label="Filter research">{["All","Stocks","Funds","Bonds","Saved"].map(f=><button aria-pressed={filter===f} key={f} onClick={()=>setFilter(f)}>{f}{f==="Saved"?` (${preferences.saved.length})`:""}</button>)}</div><span className="demo-muted" role="status">{shown.length} {shown.length===1?"idea":"ideas"}</span></div><div className="research-list">{shown.map(item=><article className="research-card" key={item.id}><details><summary><span className="research-ticker">{item.symbol}</span><span><small>{item.type} · Educational explainer</small><strong>{item.title}</strong></span><ChevronDown size={17}/></summary><div className="research-content"><p>{item.summary}</p><div><a href={item.source} target="_blank" rel="noreferrer" className="demo-link">{item.sourceLabel}<ArrowUpRight size={15}/><span className="sr-only"> Opens a new tab</span></a><Link href={`/learn/${item.lesson}`} className="demo-link">Learn the basics →</Link></div></div></details><button className={`research-save ${preferences.saved.includes(item.id)?"is-saved":""}`} aria-label={`${preferences.saved.includes(item.id)?"Unsave":"Save"} ${item.symbol}`} aria-pressed={preferences.saved.includes(item.id)} onClick={()=>save(item.id)}><Bookmark size={18} fill={preferences.saved.includes(item.id)?"currentColor":"none"}/></button></article>)}</div>{!shown.length&&<div className="demo-empty"><Search/><h3>{filter==="Saved"?"Build your reading list.":"No matching ideas yet."}</h3><p>{filter==="Saved"?"Save an explainer using its bookmark button.":"Try VTI, AAPL, bonds or funds."}</p><button className="button secondary" onClick={()=>{setQuery("");setFilter("All");}}>Explore all ideas</button></div>}<p className="demo-muted">Curated educational content, not a live news feed. Fund details can change; use the linked provider documents for current information.</p></div>;
}
