"use client";
import Link from "next/link";
import { ArrowUpRight, RefreshCw, ChevronDown, BookOpen, Users, Compass, ShieldCheck, Sparkles } from "lucide-react";
import { useState } from "react";
import { useDemo } from "./demo-provider";
import { summarizePortfolio } from "@/lib/portfolio";
import { lessons } from "@/lib/lessons";
import { sampleNews } from "@/lib/sample-data";
import { MonthlyRecapModal, RecapHomeCard } from "./recap-home";
import { recapDemoEnabled } from "@/lib/features";
const money=(value:number)=>value.toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2});
export function HomeDashboard(){
 const {portfolio,preferences,announce}=useDemo();const summary=summarizePortfolio(portfolio);const [refreshing,setRefreshing]=useState(false);const [storyIndex,setStoryIndex]=useState(0);const largest=summary.allocations[0];const contributor=summary.contributors[0];const next=lessons.find(l=>!preferences.completed.includes(l.id));const source=portfolio.source==="csv"?"CSV preview":"Sample portfolio";const day=summary.dayChange;const positive=day>=0;const topNews=portfolio.source==="sample"?sampleNews.find(item=>item.symbol===contributor?.symbol):undefined;
 const stories=[
  {eyebrow:"Your week in one sentence",title:<>Your portfolio finished <em>{positive?"higher":"lower"}.</em></>,copy:topNews?`${contributor?.symbol} led the move. ${topNews.headline}.`:`${contributor?.symbol??"Your leading holding"} drove the biggest part of the latest move in your file.`},
  {eyebrow:"What moved your money",title:<><em>{contributor?.symbol??"One holding"}</em> did most of the lifting.</>,copy:`It contributed ${contributor?.value&&contributor.value<0?"−":"+"}${money(Math.abs(contributor?.value??0))} to the latest change. See the full breakdown before drawing conclusions.`},
  {eyebrow:"The short version",title:<>A {Math.abs(summary.dayChangePercent).toFixed(2)}% move. <em>Here’s why.</em></>,copy:`Your biggest position is ${largest?.symbol??"still loading"}${largest?` at ${largest.percent.toFixed(0)}% of the portfolio`:""}. That makes its movement matter more to your total.`}
 ];const story=stories[storyIndex%stories.length];
 async function refresh(){setRefreshing(true);await new Promise(resolve=>setTimeout(resolve,350));setStoryIndex(value=>(value+1)%stories.length);setRefreshing(false);announce("Your home insight was refreshed from the same portfolio data.");}
 return <>{recapDemoEnabled&&<MonthlyRecapModal/>}<header className="home-header"><div><p className="eyebrow">A little clarity goes a long way</p><h1>Hey, {preferences.name}<span className="hello-dot">.</span></h1><p>Your money story, made simple.</p></div><div className="home-source"><span><span className="demo-dot"/>{source}</span><button aria-label="Refresh home insight" title="Show another insight" disabled={refreshing} onClick={refresh}><RefreshCw size={17} className={refreshing?"spin":""}/></button></div></header>
 <section className="home-hero"><div key={storyIndex} className="home-story" aria-live="polite"><p className="eyebrow">{story.eyebrow}</p><h2>{story.title}</h2><p>{story.copy}</p><div className="home-hero-actions"><Link href="/portfolio" className="button lime">See my portfolio <ArrowUpRight size={18}/></Link><Link href={`/discover?q=${encodeURIComponent(contributor?.symbol??"market")}`} className="button home-discover">Explore what moved it <Compass size={18}/></Link></div></div><div className="home-value"><span>Portfolio value</span><strong>{money(summary.totalValue)}</strong><p className={positive?"home-up":"home-down"}>{positive?"+":"−"}{money(Math.abs(day))} <span>({positive?"+":""}{summary.dayChangePercent.toFixed(2)}%)</span></p><small>Change vs. previous close in {portfolio.source==="csv"?"your file":"sample data"}</small><div className="allocation-ribbon" aria-label="Portfolio mix">{summary.allocations.map((a,i)=><span key={a.symbol} style={{width:`${a.percent}%`,background:["#d6f58d","#baa1f3","#f1cc75","#97c6e4"][i%4]}} title={`${a.symbol}: ${a.percent.toFixed(1)}%`}/>)}</div><Link href="/portfolio">See your holdings <ArrowUpRight size={15}/></Link></div></section>
 {recapDemoEnabled&&<RecapHomeCard/>}<div className="home-stats"><Link href="/portfolio"><strong>{portfolio.holdings.length}</strong><span>holdings in your mix</span><ArrowUpRight size={16}/></Link><Link href="/learn"><strong>{preferences.completed.length}/6</strong><span>lessons completed</span><ArrowUpRight size={16}/></Link><Link href="/social"><strong>{preferences.follows.length}</strong><span>students you follow</span><ArrowUpRight size={16}/></Link></div>
 <div className="home-lower"><section><div className="demo-toolbar"><h2 className="demo-title">Your quick briefing</h2><span className="badge">From your holdings</span></div><div className="home-briefs"><details open><summary><span className="brief-icon"><Sparkles size={18}/></span><span><strong>{positive?"A little higher.":"A down day."} Here’s the math.</strong><small>{positive?"+":"−"}{money(Math.abs(day))} across your holdings</small></span><ChevronDown size={17}/></summary><div><p>We compare each holding’s price with its previous close, multiply by the shares you own, and add the changes together.{contributor?` ${contributor.symbol} had the most positive contribution: ${contributor.value>=0?"+":"−"}${money(Math.abs(contributor.value))}.`:""}</p><Link className="demo-link" href="/portfolio">See the breakdown <ArrowUpRight size={15}/></Link></div></details><details><summary><span className="brief-icon purple"><Compass size={18}/></span><span><strong>{largest?`${largest.symbol} is your biggest piece.`:"Start with a sample portfolio."}</strong><small>{largest?`${largest.percent.toFixed(1)}% of your portfolio’s value`:"No holdings loaded"}</small></span><ChevronDown size={17}/></summary><div><p>A large holding can drive more of the portfolio’s movement. A fund may hold many companies inside it, so look at the whole mix before drawing conclusions.</p><Link className="demo-link" href="/learn/spread-your-risk">Understand your mix <ArrowUpRight size={15}/></Link></div></details><details><summary><span className="brief-icon gold"><BookOpen size={18}/></span><span><strong>{next?"One small win for today.":"You’ve built a strong foundation."}</strong><small>{next?.title??"Revisit your research checklist"}</small></span><ChevronDown size={17}/></summary><div><p>{next?.intro??"Keep checking sources, costs and what each investment adds to your mix."}</p><Link className="demo-link" href={`/learn/${next?.id??"research-checklist"}`}>{next?`Start a ${next.minutes}-minute lesson`:"Open your checklist"}<ArrowUpRight size={15}/></Link></div></details></div></section><aside className="home-community"><Users size={27}/><p className="eyebrow">Better together</p><h2>Your campus.<br/>Fresh perspectives.</h2><p>Growth, dividends or index funds? Explore the people behind different approaches.</p><div className="avatar-stack" aria-hidden="true"><span>AC</span><span>SK</span><span>MJ</span><span>+3</span></div><Link className="button secondary" href="/social">Meet the community <ArrowUpRight size={17}/></Link><small>Fictional profiles · Demo leaderboard</small></aside></div>
 <Link className="home-security" href="/settings#privacy"><ShieldCheck size={17}/><span>Explore freely. No trades or transfers, ever.</span><ArrowUpRight size={15}/></Link><p className="demo-muted">{source} · {new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric",timeZone:"America/New_York"}).format(new Date(portfolio.asOf))}. Educational information, not buy or sell instructions.</p></>;
}


