"use client";
import Link from "next/link";
import { ArrowUpRight, Check, BookOpen, Layers, TrendingUp, Globe2, FileText, ListChecks } from "lucide-react";
import { useState } from "react";
import { lessons } from "@/lib/lessons";
import { useDemo } from "./demo-provider";
const icons=[Layers,TrendingUp,Globe2,FileText,BookOpen,ListChecks];
export function LearningLibrary(){const {preferences}=useDemo();const [filter,setFilter]=useState("All lessons");const done=preferences.completed;const next=lessons.find(l=>!done.includes(l.id));const shown=lessons.filter(l=>filter==="All lessons"||(filter==="To learn"?!done.includes(l.id):done.includes(l.id)));
 return <div className="workspace"><section className="learn-banner"><div><p className="eyebrow">Build confidence, one idea at a time</p><h2>{done.length===6?<>You built your <em>foundation.</em></>:<>Less scrolling.<br/><em>More understanding.</em></>}</h2><p>Six bite-size lessons. A quick check. Something you can actually use.</p><Link href={`/learn/${next?.id??lessons[0].id}`} className="button lime">{done.length===6?"Revisit a lesson":done.length?"Keep learning":"Start your first lesson"}<ArrowUpRight size={17}/></Link></div><div className="learn-progress"><strong>{done.length}<span>/6</span></strong><p>lessons completed</p><div className="mini-progress"><span style={{width:`${done.length/6*100}%`}}/></div><small>{done.length===6?"Foundation builder unlocked":"Your progress stays in this browser"}</small></div></section><div className="demo-toolbar"><h2 className="demo-title">Your learning path</h2><div className="demo-tabs" role="group" aria-label="Filter lessons">{["All lessons","To learn","Completed"].map(f=><button key={f} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div></div><div className="demo-grid">{shown.map(l=>{const index=lessons.findIndex(x=>x.id===l.id);const Icon=icons[index];return <Link className={`learning-card tone-${l.color}`} href={`/learn/${l.id}`} key={l.id}><div className="learning-card-top"><Icon size={25}/><span>{done.includes(l.id)?<><Check size={14}/> Complete</>:`${l.minutes} min`}</span></div><span className="eyebrow">{String(index+1).padStart(2,"0")} · {l.tag}</span><h3>{l.title}</h3><p>{l.intro}</p><span className="demo-link">{done.includes(l.id)?"Review lesson":"Open lesson"}<ArrowUpRight size={16}/></span></Link>;})}</div>{!shown.length&&<div className="demo-empty"><BookOpen/><h3>{filter==="Completed"?"Your first win is one lesson away.":"You’ve finished the path."}</h3><button className="button secondary" onClick={()=>setFilter("All lessons")}>Show all lessons</button></div>}</div>;
}
