"use client";
import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2 } from "lucide-react";
import { useState } from "react";
import { lessons } from "@/lib/lessons";
import { useDemo } from "./demo-provider";
import { GrowthCalculator } from "./growth-calculator";
export function LessonReader({id}:{id:string}) {
 const lesson=lessons.find(l=>l.id===id)!;const index=lessons.findIndex(l=>l.id===id);const next=lessons[index+1];const {preferences,update,announce}=useDemo();const [answer,setAnswer]=useState<number|null>(null);const [checked,setChecked]=useState(false);const done=preferences.completed.includes(id);const correct=checked&&answer===lesson.correct;
 return <article className="lesson-reader"><Link className="demo-link" href="/learn"><ArrowLeft size={16}/> All lessons</Link><header className={`lesson-cover tone-${lesson.color}`}><p className="eyebrow">Lesson {index+1} of 6 · {lesson.minutes} min</p><h1>{lesson.title}</h1><p>{lesson.intro}</p>{done&&<span className="badge"><CheckCircle2 size={14}/> Completed</span>}</header><div className="lesson-body">{lesson.sections.map((section,i)=><section key={section.title}><span className="lesson-number">0{i+1}</span><div><h2>{section.title}</h2><p>{section.body}</p></div></section>)}<aside className="lesson-takeaway"><span className="eyebrow">Keep this with you</span><p>{lesson.takeaway}</p></aside><a className="demo-link" href={lesson.source} target="_blank" rel="noreferrer">Read more: {lesson.sourceLabel} ↗<span className="sr-only"> (opens a new tab)</span></a></div>{id==="fees-and-time"&&<GrowthCalculator/>}<section className="lesson-quiz"><p className="eyebrow">Make it stick</p><h2>One quick check.</h2><form onSubmit={e=>{e.preventDefault();if(answer!==null)setChecked(true);}}><fieldset><legend>{lesson.question}</legend>{lesson.options.map((option,i)=><label key={option} className={`quiz-option ${answer===i?"quiz-selected":""}`}><input type="radio" name="answer" checked={answer===i} onChange={()=>{setAnswer(i);setChecked(false);}}/>{option}</label>)}</fieldset><button className="button primary" disabled={answer===null}>Check answer</button></form>{checked&&<div className={`quiz-feedback ${correct?"correct":""}`} role="status"><strong>{correct?"You’ve got it.":"Almost. Give it another look."}</strong><p>{correct?lesson.explanation:"Think about the main idea above, then try again."}</p></div>}{(correct||done)&&<div className="step-actions">{!done?<button className="button primary" onClick={()=>{update({completed:[...new Set([...preferences.completed,id])]});announce("Lesson complete. One more idea in your toolkit.");}}>Mark lesson complete <CheckCircle2 size={16}/></button>:<span className="demo-link"><CheckCircle2 size={17}/> Lesson completed</span>}{done&&<Link className="button secondary" href={next?`/learn/${next.id}`:"/learn"}>{next?"Next lesson":"View your progress"}<ArrowRight size={16}/></Link>}</div>}</section></article>;
}
