"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useRef, useState, type ChangeEvent } from "react";
import { Upload, Sparkles, ShieldCheck, CheckCircle2, ArrowRight } from "lucide-react";
import { useDemo, type DemoPreferences } from "./demo-provider";
import { samplePortfolio } from "@/lib/sample-data";
import { parseHoldingsCsv } from "@/lib/csv";
import type { Holding } from "@/lib/domain";
type PlaidHandler={open:()=>void;destroy:()=>void};
declare global { interface Window { Plaid?:{create:(options:{token:string;onSuccess:(publicToken:string,metadata:{institution?:{name?:string}})=>void;onExit:()=>void})=>PlaidHandler} } }
async function loadPlaid(){if(window.Plaid)return window.Plaid;await new Promise<void>((resolve,reject)=>{const existing=document.querySelector<HTMLScriptElement>('script[data-cornerstone-plaid]');if(existing){existing.addEventListener("load",()=>resolve(),{once:true});existing.addEventListener("error",()=>reject(new Error("Plaid Link could not load.")),{once:true});return}const script=document.createElement("script");script.src="https://cdn.plaid.com/link/v2/stable/link-initialize.js";script.async=true;script.dataset.cornerstonePlaid="true";script.onload=()=>resolve();script.onerror=()=>reject(new Error("Plaid Link could not load."));document.head.append(script)});if(!window.Plaid)throw new Error("Plaid Link is unavailable.");return window.Plaid}
export function OnboardingFlow(){
 const router=useRouter();const {preferences,update,setPortfolio,announce}=useDemo();const [step,setStep]=useState(1);const [editedName,setName]=useState<string|null>(null);const [editedCollege,setCollege]=useState<string|null>(null);const [editedLevel,setLevel]=useState<DemoPreferences["level"]|null>(null);const [editedGoal,setGoal]=useState<DemoPreferences["goal"]|null>(null);const [status,setStatus]=useState("");const [holdings,setHoldings]=useState<Holding[]|null>(null);const [reading,setReading]=useState(false);const dialog=useRef<HTMLDialogElement>(null);const name=editedName??preferences.name,college=editedCollege??preferences.college,level=editedLevel??preferences.level,goal=editedGoal??preferences.goal;
 function persist(){update({name:name.trim()||"Alex",college:college.trim()||"Your university",level,goal});}
 async function csv(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;setHoldings(null);setStatus("");setReading(true);try{if(file.size>2_000_000)throw new Error("Choose a CSV smaller than 2 MB.");const parsed=parseHoldingsCsv(await file.text());if(parsed.length>50)throw new Error("This demo supports up to 50 holdings. Try a smaller export.");setHoldings(parsed);setStatus(`${parsed.length} holdings validated. Nothing was uploaded.`);}catch(error){setStatus(error instanceof Error?error.message:"We couldn’t read that file. Try the example CSV.");}finally{setReading(false);event.target.value="";}}
 function openSample(){persist();setPortfolio(samplePortfolio);announce("Your demo is ready. Explore without connecting an account.");router.push("/");}
 async function connectBrokerage(){setStatus("Preparing a secure read-only connection…");try{const response=await fetch("/api/plaid/link-token",{method:"POST"});const body=await response.json();if(!response.ok||!body.linkToken)throw new Error(body.reason||"Account linking is unavailable.");const plaid=await loadPlaid();const handler:PlaidHandler=plaid.create({token:body.linkToken,onSuccess:async(publicToken,metadata)=>{setStatus("Building your history…");const exchange=await fetch("/api/plaid/exchange",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({publicToken,institutionName:metadata.institution?.name||"Connected brokerage"})});const result=await exchange.json();if(!exchange.ok){setStatus(result.reason||"The account could not be connected.");return}setStatus(result.message||"Building your history.");handler.destroy()},onExit:()=>{setStatus("No account was connected.");handler.destroy()}});handler.open()}catch(error){setStatus(error instanceof Error?error.message:"Account linking is unavailable.")}}
 return <div className="onboarding"><div className="onboarding-top"><span>Make it yours</span><span>{step} of 3</span></div><div className="progress-line" aria-label={`Step ${step} of 3`}><span style={{width:`${step/3*100}%`}}/></div>
 {step===1&&<section><p className="eyebrow">First, a quick hello</p><h1>Meet your money era.</h1><p className="muted">A demo profile, just for this browser. Pick a nickname and make yourself at home.</p><form onSubmit={e=>{e.preventDefault();setStep(2);}}><div className="demo-form-grid workspace"><label className="demo-label">Nickname<input className="demo-input" required maxLength={40} value={name} onChange={e=>setName(e.target.value)} /></label><label className="demo-label">College<input className="demo-input" maxLength={80} value={college} onChange={e=>setCollege(e.target.value)} placeholder="Your university"/></label></div><h2 className="setup-question">Where are you starting?</h2><div className="choice-grid">{[["New","Just getting started."],["Growing","I invest and want to learn."],["Experienced","I want a clearer picture."]].map(([title,copy])=><button type="button" key={title} className={`choice ${level===title?"choice-selected":""}`} aria-pressed={level===title} onClick={()=>setLevel(title as DemoPreferences["level"])}><strong>{title}</strong><span>{copy}</span></button>)}</div><div className="step-actions"><Link className="demo-link" href="/">Skip for now</Link><button className="button primary">Continue <ArrowRight size={17}/></button></div></form></section>}
 {step===2&&<section><p className="eyebrow">Make room for your goals</p><h1>What brings you here?</h1><p className="muted">We’ll put a useful next step on your home page.</p><div className="choice-grid workspace">{[["Understand","Get to know what I own."],["Research","Find my next research idea."],["Stay consistent","Build a learning habit."]].map(([title,copy])=><button key={title} aria-pressed={goal===title} className={`choice ${goal===title?"choice-selected":""}`} onClick={()=>setGoal(title as DemoPreferences["goal"])}><strong>{title}</strong><span>{copy}</span></button>)}</div><div className="step-actions"><button className="button secondary" onClick={()=>setStep(1)}>Back</button><button className="button primary" onClick={()=>{persist();setStep(3);}}>Continue <ArrowRight size={17}/></button></div></section>}
 {step===3&&<section><p className="eyebrow">You’re one step away</p><h1>Take it for a spin.</h1><p className="muted">Start with the sample portfolio, or preview a CSV on this device.</p><button className="sample-start" onClick={openSample}><Sparkles size={30}/><span><strong>Launch the sample portfolio</strong><small>Four holdings. A full tour. No account needed.</small></span><ArrowRight size={23}/></button><div className="setup-secondary"><section className="demo-card"><Upload size={23}/><h2>Try your own CSV</h2><p>Prices stay exactly as supplied in the file. Your preview is held in memory and clears when you reload.</p><a className="demo-link" download="cornerstone-example.csv" href="/demo-portfolio.csv">Download example CSV ↓</a><label className="demo-label workspace">Choose CSV (up to 2 MB, 50 holdings)<input className="csv-input" type="file" accept=".csv,text/csv" onChange={csv} disabled={reading}/></label><details className="csv-help"><summary>What columns do I need?</summary><p>Required: symbol, name, quantity, price. Optional: previous_close, cost_basis (total cost), sector, asset_class (equity, fund, fixed-income, cash). One row per symbol. Missing previous close uses the current price, so its daily change is zero.</p></details></section><section className="demo-card"><ShieldCheck size={23}/><h2>Brokerage linking</h2><p>Connect read-only investment data when Plaid and secure storage are configured. You can always explore with sample holdings.</p><button className="button primary" onClick={connectBrokerage}>Connect brokerage</button><button className="demo-link workspace" onClick={()=>dialog.current?.showModal()}>How linking works</button></section></div>{reading&&<p role="status" className="demo-status">Checking your file…</p>}{status&&<p className="demo-status" role="status">{status}</p>}{holdings&&<section className="demo-card workspace"><h2><CheckCircle2 size={22}/> Your preview is ready</h2><p>{holdings.length} holdings · {holdings.reduce((sum,h)=>sum+h.quantity*h.price,0).toLocaleString("en-US",{style:"currency",currency:"USD"})} total value</p><div className="csv-preview">{holdings.slice(0,6).map(h=><span key={h.symbol}>{h.symbol} · {h.quantity} shares</span>)}{holdings.length>6&&<span>+{holdings.length-6} more</span>}</div><button className="button primary" onClick={()=>{persist();setPortfolio({id:`csv-${Date.now()}`,source:"csv",institution:"Local CSV preview",asOf:new Date().toISOString(),freshness:"stale",currency:"USD",holdings});announce("CSV preview opened. It stays on this page session and clears on reload.");router.push("/portfolio");}}>Use this portfolio <ArrowRight size={17}/></button></section>}<div className="step-actions"><button className="button secondary" onClick={()=>setStep(2)}>Back</button><Link className="demo-link" href="/">Back to home</Link></div></section>}
 <dialog ref={dialog} className="demo-dialog"><h2>See your portfolio. Keep control.</h2><p>A connected account requests read-only investment access. Cornerstone will not place trades or move money. The demo currently supports sample holdings and local CSV previews.</p><form method="dialog"><button className="button primary">Got it</button></form></dialog></div>;
}
