"use client";

import { ArrowRight, CalendarDays, Check, Clock3, Crown, Flame, LockKeyhole, Pencil, Plus, Save, ShieldCheck, Sparkles, Target, Trash2, TrendingUp, Trophy, X } from "lucide-react";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { GrowthCalculator } from "./growth-calculator";
import { RecapShareCard } from "./recap-share-card";
import { useDemo } from "./demo-provider";
import { contributionSeries, formatMonth, isPossibleDuplicate, latestContributionMonth, monthKeyInTimeZone, shiftMonth, summarizeRecap, type ContributionEvent, type ContributionKind } from "@/lib/recap";
import { captureSafeEvent } from "@/lib/analytics";

const money=(value:number)=>value.toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});

function CampusProgress({serverMode,checked,onChange}:{serverMode:boolean;checked:boolean;onChange:(checked:boolean)=>void}){
  const [result,setResult]=useState<{percentile:number;cohortSize:string}|null>(null);
  useEffect(()=>{if(!serverMode)return;fetch("/api/campus/cohort").then(async response=>{if(response.ok){const body=await response.json();if(body.available)setResult(body)}}).catch(()=>undefined)},[serverMode]);
  return <section className="demo-card campus-recap">
    <Sparkles/>
    <p className="eyebrow">{serverMode?result?`Campus cohort · ${result.cohortSize}`:"Your own pace":"Sample campus view"}</p>
    <h2>{serverMode?result?`${result.percentile}%`:"Private":"68%"}</h2>
    <p>{serverMode?result?`Your consistency is at or above ${result.percentile}% of your eligible campus cohort. No dollar amounts are compared.`:"Your personal progress stays front and center until you opt in, verify your school and your cohort is large enough.":"More consistent than 68% of an illustrative 30–49 student cohort. Real comparisons use six months of confirmed activity and never compare dollar amounts."}</p>
    {!serverMode&&<label className="preference-row"><span><strong>Campus comparison</strong><small>Demo preference only; no email is verified.</small></span><input type="checkbox" role="switch" checked={checked} onChange={event=>onChange(event.target.checked)}/></label>}
  </section>
}

export function RecapWorkspace(){
  const {contributions,setContributions,contributionMode,recapTimezone,preferences,update,announce}=useDemo();
  const [selectedPeriod,setSelectedPeriod]=useState<string|null>(null);
  const [amount,setAmount]=useState("");
  const [date,setDate]=useState(()=>new Date().toISOString().slice(0,10));
  const [manualKind,setManualKind]=useState<ContributionKind>("contribution");
  const [duplicate,setDuplicate]=useState(false);
  const [editing,setEditing]=useState<{id:string;amount:string;date:string}|null>(null);
  const [editDuplicate,setEditDuplicate]=useState(false);
  const [proPreview,setProPreview]=useState(false);
  const [billingStatus,setBillingStatus]=useState("");
  const [billingPeriod,setBillingPeriod]=useState<"monthly"|"annual">("monthly");
  const [revision,setRevision]=useState<number|null>(null);
  const [isPro,setIsPro]=useState(false);
  const [historyMonths,setHistoryMonths]=useState(6);
  const [customMilestone,setCustomMilestone]=useState("2500");
  const [rewardMessage,setRewardMessage]=useState("");
  const serverMode=contributionMode==="server";
  const latest=serverMode?monthKeyInTimeZone(new Date(),recapTimezone):latestContributionMonth(contributions);
  const period=selectedPeriod??latest;
  const summary=useMemo(()=>summarizeRecap(contributions,period),[contributions,period]);
  const suggested=contributions.filter(event=>event.status==="suggested");
  const manualEntries=contributions.filter(event=>event.source==="manual"&&event.status!=="deleted").sort((a,b)=>b.occurredOn.localeCompare(a.occurredOn));
  const fullHistory=serverMode?isPro:proPreview;
  const history=fullHistory?contributionSeries(contributions,period,historyMonths):summary.months.slice(-3);
  const largest=Math.max(1,...history.map(month=>month.contributed));
  const milestoneRemaining=Math.max(0,summary.nextMilestone-summary.lifetimeContributed);
  const milestoneProgress=Math.min(100,summary.lifetimeContributed/summary.nextMilestone*100);
  const comparisonPercent=summary.previousContributed>0?Math.round(summary.changeFromPrevious/summary.previousContributed*100):null;
  const chartPoints=history.map((month,index)=>({month,x:34+index*(572/Math.max(1,history.length-1)),y:178-month.contributed/largest*124}));
  const chartLine=chartPoints.map((point,index)=>`${index?"L":"M"} ${point.x} ${point.y}`).join(" ");
  const chartArea=chartPoints.length?`${chartLine} L ${chartPoints.at(-1)?.x} 190 L ${chartPoints[0].x} 190 Z`:"";

  useEffect(()=>{if(!serverMode)return;let active=true;fetch("/api/recaps").then(async response=>{if(!response.ok||!active)return;const body=await response.json();const found=(body.recaps??[]).find((recap:Record<string,unknown>)=>recap.period_kind==="monthly"&&String(recap.period_start).slice(0,7)===period);setRevision(found?Number(found.revision):null);setIsPro(Boolean(body.isPro))}).catch(()=>undefined);return()=>{active=false}},[serverMode,period]);
  useEffect(()=>{if(!serverMode||!isPro)return;fetch("/api/recap-preferences").then(async response=>{if(!response.ok)return;const body=await response.json();const milestones=body.preferences?.custom_milestones;if(Array.isArray(milestones)&&milestones.length)setCustomMilestone(String(milestones.at(-1)))}).catch(()=>undefined)},[serverMode,isPro]);
  useEffect(()=>{if(!rewardMessage)return;const timer=window.setTimeout(()=>setRewardMessage(""),4500);return()=>window.clearTimeout(timer)},[rewardMessage]);

  async function classify(id:string,status:"confirmed"|"excluded"){
    const activity=contributions.find(event=>event.id===id);
    if(serverMode){const response=await fetch(`/api/contributions/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status})});const body=await response.json();if(!response.ok){announce(body.reason||"Activity could not be updated.");return}setRevision(Number(body.recap?.revision)||null)}
    setContributions(events=>events.map(event=>event.id===id?{...event,status,userCorrected:true}:event));if(status==="confirmed"&&activity){const unlocked=summary.lifetimeContributed+activity.amount>=summary.nextMilestone;setRewardMessage(unlocked?`${money(summary.nextMilestone)} milestone unlocked!`:`+${money(activity.amount)} added to your month`)}announce(status==="confirmed"?"Activity confirmed and your recap was recalculated.":"Activity excluded from your recap.");captureSafeEvent("classification_corrected");
  }

  function addManual(event:FormEvent){event.preventDefault();const value=Number(amount);if(!Number.isFinite(value)||value<=0){announce("Enter an amount greater than $0.");return}if(isPossibleDuplicate(contributions,{amount:value,occurredOn:date})){setDuplicate(true);return}void commitManual(value)}

  async function commitManual(value=Number(amount),allowDuplicate=false){
    let item:ContributionEvent={id:`manual-${Date.now()}`,occurredOn:date,amount:value,currency:"USD",kind:manualKind,status:"confirmed",source:"manual",userCorrected:true};
    if(serverMode){const response=await fetch("/api/contributions",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({amount:value,occurredOn:date,kind:manualKind,allowDuplicate})});const body=await response.json();if(!response.ok){if(response.status===409)setDuplicate(true);else announce(body.reason||"Activity could not be saved.");return}const row=body.contribution;item={...item,id:String(row.id)};setRevision(Number(body.recap?.revision)||null)}
    setContributions(events=>[...events,item]);if(manualKind==="contribution"){const unlocked=summary.lifetimeContributed+value>=summary.nextMilestone;setRewardMessage(unlocked?`${money(summary.nextMilestone)} milestone unlocked!`:`+${money(value)} added to your month`)}setAmount("");setDuplicate(false);setSelectedPeriod(date.slice(0,7));announce(serverMode?"Activity saved and your recap was recalculated.":"Manual activity added to this session.");
  }

  function beginEdit(entry:ContributionEvent){setEditing({id:entry.id,amount:String(entry.amount),date:entry.occurredOn});setEditDuplicate(false)}

  async function saveManual(allowDuplicate=false){
    if(!editing)return;const value=Number(editing.amount);if(!Number.isFinite(value)||value<=0){announce("Enter an amount greater than $0.");return}if(!allowDuplicate&&isPossibleDuplicate(contributions,{amount:value,occurredOn:editing.date},editing.id)){setEditDuplicate(true);return}
    if(serverMode){const response=await fetch(`/api/contributions/${editing.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({amount:value,occurredOn:editing.date,allowDuplicate})});const body=await response.json();if(!response.ok){if(response.status===409)setEditDuplicate(true);else announce(body.reason||"Activity could not be updated.");return}setRevision(Number(body.recap?.revision)||null)}
    setContributions(events=>events.map(event=>event.id===editing.id?{...event,amount:value,occurredOn:editing.date,userCorrected:true}:event));setSelectedPeriod(editing.date.slice(0,7));setEditing(null);setEditDuplicate(false);announce("Manual activity updated. The recap revision is marked.");
  }

  async function deleteManual(entry:ContributionEvent){
    if(serverMode){const response=await fetch(`/api/contributions/${entry.id}`,{method:"DELETE"});const body=await response.json();if(!response.ok){announce(body?.reason||"Activity could not be removed.");return}setRevision(Number(body?.recap?.revision)||null)}
    setContributions(events=>events.map(event=>event.id===entry.id?{...event,status:"deleted",userCorrected:true}:event));if(editing?.id===entry.id)setEditing(null);announce("Manual activity removed. Earlier recap snapshots stay in your history.");
  }

  async function checkout(){captureSafeEvent("trial_started");setBillingStatus("Opening secure checkout…");try{const response=await fetch("/api/billing/checkout",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({price:billingPeriod})});const body=await response.json();if(!response.ok)throw new Error(body.reason||"Checkout is unavailable.");location.href=body.url}catch(error){setBillingStatus(error instanceof Error?error.message:"Checkout is unavailable.")}}

  async function saveMilestone(){const value=Number(customMilestone);if(!Number.isFinite(value)||value<=summary.lifetimeContributed){announce("Choose a milestone above your confirmed total.");return}if(serverMode){if(!isPro){announce("Custom milestones unlock with Pro.");return}const response=await fetch("/api/recap-preferences",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({customMilestones:[value]})});if(!response.ok){announce((await response.json()).reason||"Milestone could not be saved.");return}}announce(serverMode?"Your custom milestone was saved.":"Custom milestone added to the Pro preview.")}

  return <div className="workspace recap-workspace">
    <section className="recap-dashboard">{rewardMessage&&<div className="recap-reward-toast" role="status"><Trophy/> {rewardMessage}</div>}<div className="recap-win-copy"><span className="recap-win-pill"><Sparkles/> {summary.streak?`Month ${summary.streak} unlocked`:"Your month, your pace"}</span><p className="eyebrow">{formatMonth(period)} {contributionMode==="sample"&&<span className="recap-source">Sample</span>}</p><h2>{money(summary.contributed)}</h2><strong>{summary.contributed>0?"You added to your future.":"This month is part of your story."}</strong><p>{summary.streak?`That’s ${summary.streak} months of showing up.`:"A quieter month never erases earlier progress."}</p>{summary.contributed>0&&<div className="recap-month-win"><TrendingUp/><span><strong>{comparisonPercent===null?"A fresh start":`${summary.changeFromPrevious>=0?"+":"−"}${Math.abs(comparisonPercent)}%`}</strong>{comparisonPercent===null?" for this month":` from ${formatMonth(shiftMonth(period,-1),"short")}`}</span></div>}{revision&&<small className="recap-revision">{revision>1?`Updated recap · revision ${revision}`:"Recap snapshot · revision 1"}</small>}</div><div className="recap-reward-panel"><div className="recap-milestone-score"><span><Target/></span><div><small>Milestone progress</small><strong>{milestoneProgress.toFixed(0)}%</strong></div></div><div className="recap-reward-track"><span style={{width:`${milestoneProgress}%`}}/></div><p><strong>{money(milestoneRemaining)}</strong> until {money(summary.nextMilestone)}</p><div className="recap-streak-celebration"><Flame/><div><strong>{summary.streak} month streak</strong><small>{summary.streak?"Keep the chain glowing":"Your next contribution starts a streak"}</small></div><div className="recap-streak-dots" aria-hidden="true">{[1,2,3,4].map(value=><i key={value} className={value<=summary.streak?"active":""}/>)}</div></div></div><div className="recap-dashboard-stats"><div><small>Ready to review</small><strong>{summary.pending}</strong></div><div><small>Money out this month</small><strong>{money(summary.withdrawn)}</strong></div></div></section>
    <div className="recap-columns"><main className="demo-stack">
      <section className="demo-card recap-trend-card"><div className="demo-toolbar"><div><p className="eyebrow">Your momentum</p><h2>{fullHistory?`${history.length} months in view.`:"Three months. Still moving."}</h2></div><div className="recap-period-nav"><button aria-label="Previous month" onClick={()=>setSelectedPeriod(shiftMonth(period,-1))}>←</button><button aria-label="Next month" onClick={()=>setSelectedPeriod(shiftMonth(period,1))}>→</button></div></div><div className="recap-trend-summary"><span><TrendingUp/></span><div><strong>{comparisonPercent===null?"Your first step counts":`${summary.changeFromPrevious>=0?"Up":"Down"} ${Math.abs(comparisonPercent)}% from last month`}</strong><small>{comparisonPercent===null?"Keep adding chapters to see your pattern.":`${money(summary.contributed)} added in ${formatMonth(period,"short")}`}</small></div></div><div className="recap-line-chart" aria-label="Contribution history"><svg viewBox="0 0 640 205" role="img"><title>Monthly confirmed contribution trend</title><defs><linearGradient id="recap-area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#9dd84a" stopOpacity=".62"/><stop offset="1" stopColor="#9dd84a" stopOpacity="0"/></linearGradient></defs><path className="recap-chart-grid" d="M34 54 H606 M34 116 H606 M34 178 H606"/><path className="recap-chart-area" d={chartArea}/><path className="recap-chart-line" d={chartLine}/>{chartPoints.map(point=><g key={point.month.period} className={point.month.period===period?"selected":""}><circle className="recap-chart-halo" cx={point.x} cy={point.y} r="11"/><circle className="recap-chart-point" cx={point.x} cy={point.y} r="6"/></g>)}</svg><div className="recap-chart-labels" style={{gridTemplateColumns:`repeat(${history.length},minmax(54px,1fr))`}}>{history.map(month=><button key={month.period} className={month.period===period?"selected":""} onClick={()=>setSelectedPeriod(month.period)} aria-label={`Show ${formatMonth(month.period)} recap, ${money(month.contributed)} contributed`}><small>{formatMonth(month.period,"short").split(" ")[0]}</small><strong>{money(month.contributed)}</strong></button>)}</div></div>{!fullHistory&&<div className="recap-lock"><Crown size={19}/><span>Your latest three months are free. Pro reveals the full pattern.</span></div>}</section>
      {!isPro&&!proPreview&&<section className="recap-pro-gate"><div className="recap-pro-gate-heading"><span className="pro-label"><Crown/> Cornerstone Pro</span><h2>There’s more hiding in your pattern.</h2><p>Unlock the moments, trends and targets that make it easier to keep going.</p></div><div className="recap-locked-grid"><article><span><CalendarDays/> Strongest week</span><div className="locked-stat" aria-hidden="true">••••••</div><p>Find the seven days when you built the most momentum.</p></article><article><span><TrendingUp/> Consistency trend</span><div className="locked-stat" aria-hidden="true">••••</div><p>See whether your contribution habit is getting stronger.</p></article><article><span><Target/> Custom milestone</span><div className="locked-stat" aria-hidden="true">•••••</div><p>Choose a goal and track the distance in real time.</p></article></div><div className="recap-trial-row"><div><strong>14 days free</strong><small>Then {billingPeriod==="monthly"?"$4.99/month":"$39.99/year"}. Cancel anytime.</small></div><div className="billing-period" aria-label="Billing period"><button aria-pressed={billingPeriod==="monthly"} onClick={()=>setBillingPeriod("monthly")}>Monthly</button><button aria-pressed={billingPeriod==="annual"} onClick={()=>setBillingPeriod("annual")}>Yearly</button></div><button className="button lime" onClick={checkout}><LockKeyhole/> Start free trial</button>{contributionMode==="sample"&&<button className="demo-link pro-sample-link" onClick={()=>setProPreview(true)}>See a sample preview <ArrowRight/></button>}</div>{billingStatus&&<p className="pro-status" role="status">{billingStatus}</p>}</section>}
      {suggested.length>0&&<section className="demo-card"><p className="eyebrow">A quick check</p><h2>Did you add this money?</h2><p>We suggest likely contributions. Nothing counts until you confirm it.</p><div className="contribution-review">{suggested.map(event=><div key={event.id}><span className="recap-orb small"><Clock3/></span><div><strong>{money(event.amount)}</strong><small>{event.occurredOn} · {event.accountName??"Connected account"} · Suggested</small></div><button className="icon-button approve" aria-label={`Confirm ${money(event.amount)} contribution`} onClick={()=>void classify(event.id,"confirmed")}><Check/></button><button className="icon-button" aria-label={`Exclude ${money(event.amount)} activity`} onClick={()=>void classify(event.id,"excluded")}><X/></button></div>)}</div></section>}
      <section className="demo-card"><p className="eyebrow">Add it yourself</p><h2>Log cash activity.</h2><p>{serverMode?"This entry is saved to your private contribution history.":"Manual entries stay in memory in this demo and clear on reload. Sign in to save them."}</p><form className="manual-contribution" onSubmit={addManual}><label className="demo-label">Type<select className="demo-input" value={manualKind} onChange={event=>setManualKind(event.target.value as ContributionKind)}><option value="contribution">Money added</option><option value="withdrawal">Money withdrawn</option></select></label><label className="demo-label">Amount<input className="demo-input" type="number" min="0.01" max="10000000" step="0.01" value={amount} onChange={event=>setAmount(event.target.value)} placeholder="$100"/></label><label className="demo-label">Date<input className="demo-input" type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><button className="button primary"><Plus size={17}/> Add activity</button></form>{duplicate&&<div className="duplicate-warning" role="alert"><strong>This looks familiar.</strong><p>Activity with the same amount appears within two days. Add it only if it is separate.</p><button className="button secondary" onClick={()=>void commitManual(Number(amount),true)}>Add anyway</button><button className="demo-link" onClick={()=>setDuplicate(false)}>Cancel</button></div>}</section>
      {manualEntries.length>0&&<section className="demo-card"><p className="eyebrow">Manual activity</p><h2>Entries you control.</h2><div className="manual-entry-list">{manualEntries.map(entry=><div key={entry.id}>{editing?.id===entry.id?<><label className="demo-label">Edit amount<input className="demo-input" type="number" min=".01" value={editing.amount} onChange={event=>setEditing({...editing,amount:event.target.value})}/></label><label className="demo-label">Edit date<input className="demo-input" type="date" value={editing.date} onChange={event=>setEditing({...editing,date:event.target.value})}/></label><div className="manual-entry-actions"><button className="icon-button approve" aria-label={`Save ${money(entry.amount)} activity`} onClick={()=>void saveManual()}><Save/></button><button className="icon-button" aria-label="Cancel editing" onClick={()=>{setEditing(null);setEditDuplicate(false)}}><X/></button></div>{editDuplicate&&<div className="duplicate-warning" role="alert"><strong>This may be a duplicate.</strong><button className="demo-link" onClick={()=>void saveManual(true)}>Save anyway</button></div>}</>:<><span><strong>{entry.kind==="withdrawal"?"−":"+"}{money(entry.amount)}</strong><small>{entry.occurredOn} · {entry.kind==="contribution"?"Money added":"Money withdrawn"}</small></span><div className="manual-entry-actions"><button className="icon-button" aria-label={`Edit ${money(entry.amount)} activity`} onClick={()=>beginEdit(entry)}><Pencil/></button><button className="icon-button" aria-label={`Delete ${money(entry.amount)} activity`} onClick={()=>void deleteManual(entry)}><Trash2/></button></div></>}</div>)}</div></section>}
      <section className="demo-card"><p className="eyebrow">Share the habit</p><h2>Your number. Your choice.</h2><RecapShareCard summary={summary} source={serverMode?"server":"sample"}/></section>
      {(proPreview||isPro)&&<section className="recap-pro-preview"><div className="pro-label"><Crown/> {isPro?"Pro insights":"Sample Pro preview"}</div><h2>Your progress, with the pattern revealed.</h2><p>Weekly recaps spotlight the same habit in smaller chapters. Explore a future scenario with assumptions you choose; it is educational, not a forecast.</p><div className="recap-revealed-stats"><div><CalendarDays/><small>Strongest week</small><strong>Sep 1–7</strong></div><div><TrendingUp/><small>Consistency trend</small><strong>3 months rising</strong></div><div><Target/><small>Standard milestone</small><strong>{money(milestoneRemaining)} away</strong></div></div><div className="recap-pro-controls"><label className="demo-label">History window<select className="demo-input" value={historyMonths} disabled={serverMode&&!isPro} onChange={event=>setHistoryMonths(Number(event.target.value))}><option value="6">6 months</option><option value="12">12 months</option><option value="24">24 months</option></select></label><label className="demo-label">Personal milestone<input className="demo-input" type="number" min={Math.ceil(summary.lifetimeContributed+1)} max="100000000" value={customMilestone} disabled={serverMode&&!isPro} onChange={event=>setCustomMilestone(event.target.value)}/></label><button className="button ghost-light" disabled={serverMode&&!isPro} onClick={()=>void saveMilestone()}>Save milestone</button></div><p className="custom-milestone-status">{money(Math.max(0,Number(customMilestone||0)-summary.lifetimeContributed))} until this personal milestone.</p><div className="weekly-preview"><span>Example week</span><strong>$240</strong><small>One confirmed sample contribution</small></div><GrowthCalculator/>{!isPro&&<button className="demo-link pro-preview-close" onClick={()=>setProPreview(false)}>Hide sample preview</button>}</section>}
    </main><aside className="demo-stack">
      <section className="demo-card recap-milestone"><Trophy/><p className="eyebrow">All-time {serverMode?"confirmed":"sample"}</p><h2>{money(summary.lifetimeContributed)}</h2><p>Confirmed contributions through {formatMonth(period)}.</p><div className="recap-progress"><span style={{width:`${Math.min(100,summary.lifetimeContributed/summary.nextMilestone*100)}%`}}/></div><small>{money(summary.nextMilestone-summary.lifetimeContributed)} to your next milestone</small></section>
      <CampusProgress serverMode={serverMode} checked={preferences.campusComparison} onChange={campusComparison=>update({campusComparison})}/>
      <section className="demo-card"><ShieldCheck/><h3>What counts?</h3><p>Confirmed external contributions. Buys, sales, dividends, reinvestments, fees, rollovers and internal transfers do not count.</p></section>
    </aside></div>
  </div>
}
