"use client";
import Link from "next/link";
import { ArrowRight, CalendarDays, Check, Clock3, Sparkles, TrendingUp, Trophy } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useDemo } from "./demo-provider";
import { RecapShareCard } from "./recap-share-card";
import { formatMonth, latestContributionMonth, monthKeyInTimeZone, progressMessage, shiftMonth, summarizeRecap } from "@/lib/recap";
import { captureSafeEvent } from "@/lib/analytics";
const money=(value:number)=>value.toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});

export function RecapHomeCard(){const {contributions,contributionMode,recapTimezone}=useDemo();const period=contributionMode==="server"?monthKeyInTimeZone(new Date(),recapTimezone):latestContributionMonth(contributions);const summary=summarizeRecap(contributions,period);const progress=Math.min(100,summary.lifetimeContributed/summary.nextMilestone*100);return <section className="recap-home-card"><div className="recap-home-icon"><TrendingUp/></div><div><p className="eyebrow">Your month so far {contributionMode==="sample"&&<span className="recap-source">Sample</span>}</p><h2>{money(summary.contributed)}</h2><strong>{summary.contributed>0?"You added to your future.":"Your month is ready when you are."}</strong><p>{progressMessage(summary)} {summary.pending?`${summary.pending} activity item needs a quick check.`:"Everything is up to date."}</p><div className="recap-progress" aria-label={`${money(summary.lifetimeContributed)} of ${money(summary.nextMilestone)} milestone`}><span style={{width:`${progress}%`}}/></div><small>{money(summary.nextMilestone-summary.lifetimeContributed)} until your {money(summary.nextMilestone)} milestone</small></div><Link href="/recap">Open my recap <ArrowRight size={17}/></Link></section>}

export function MonthlyRecapModal(){const {contributions,contributionMode,recapTimezone,preferences,update}=useDemo();const current=contributionMode==="server"?monthKeyInTimeZone(new Date(),recapTimezone):latestContributionMonth(contributions);const period=shiftMonth(current,-1);const summary=summarizeRecap(contributions,period);const dialog=useRef<HTMLDialogElement>(null);const [step,setStep]=useState(0);const [campus,setCampus]=useState<{percentile:number;cohortSize:string}|null>(null);const slides=[
 <div key="money" className="recap-slide center"><span className="recap-orb"><Sparkles/></span><p className="eyebrow">Your {formatMonth(period)} recap</p><strong className="recap-big-number">{money(summary.contributed)}</strong><h2>You added to your future.</h2><p>{progressMessage(summary)}</p></div>,
 <div key="streak" className="recap-slide"><span className="recap-orb purple"><CalendarDays/></span><p className="eyebrow">Consistency looks good on you</p><h2>{summary.streak} months.<br/>Still showing up.</h2><div className="recap-month-dots">{summary.months.map(month=><span key={month.period} className={month.active?"active":""}><Check/><small>{formatMonth(month.period,"short").split(" ")[0]}</small></span>)}</div><p>A quieter month never erases the progress you already made.</p></div>,
 <div key="milestone" className="recap-slide center"><span className="recap-orb gold"><Trophy/></span><p className="eyebrow">Next milestone</p><strong className="recap-big-number">{money(summary.nextMilestone)}</strong><h2>Your next chapter.</h2><p>{money(summary.lifetimeContributed)} in confirmed {contributionMode==="sample"?"sample ":""}contributions so far.</p></div>,
 <div key="change" className="recap-slide"><span className="recap-orb"><TrendingUp/></span><p className="eyebrow">Month to month</p><h2>{summary.changeFromPrevious>=0?"You added a little more.":"Every month can look different."}</h2><div className="recap-compare"><div><small>{formatMonth(shiftMonth(period,-1),"short")}</small><strong>{money(summary.previousContributed)}</strong></div><ArrowRight/><div><small>{formatMonth(period,"short")}</small><strong>{money(summary.contributed)}</strong></div></div>{summary.withdrawn>0&&<p>{money(summary.withdrawn)} was withdrawn in this sample month. It does not erase your contribution streak.</p>}</div>,
 <div key="time" className="recap-slide"><span className="recap-orb purple"><Clock3/></span><p className="eyebrow">Give it time</p><h2>Compounding rewards patience.</h2><p>Money left invested can earn returns, and later returns can build on earlier ones. Real markets vary, so explore the math with assumptions you control.</p><Link className="demo-link" href="/learn/fees-and-time">Try the growth calculator <ArrowRight size={15}/></Link></div>,
 <div key="campus" className="recap-slide"><span className="recap-orb gold"><Trophy/></span><p className="eyebrow">{contributionMode==="sample"?"Sample campus comparison":campus?`Campus cohort · ${campus.cohortSize}`:"Your own pace"}</p><strong className="recap-big-number">{contributionMode==="sample"?"68%":campus?`${campus.percentile}%`:"Private"}</strong><h2>Consistency, not wealth.</h2><p>{contributionMode==="sample"?"This illustrates an anonymous campus percentile. A real result appears only after you opt in, verify a school email, build six months of history and join at least 29 other eligible students.":campus?`Your consistency is at or above ${campus.percentile}% of your eligible campus cohort. No dollar amounts are compared.`:"We’ll keep this about your personal progress unless you opt in and your anonymous campus group is large enough."}</p></div>,
 <div key="share" className="recap-slide"><p className="eyebrow">Yours to keep</p><h2>Share the habit.<br/>Keep the number private.</h2><RecapShareCard summary={summary} compact source={contributionMode==="server"?"server":"sample"}/></div>
 ];
 useEffect(()=>{if(contributionMode==="server")fetch("/api/campus/cohort").then(async response=>{if(response.ok){const body=await response.json();if(body.available)setCampus(body)}}).catch(()=>undefined)},[contributionMode]);
 useEffect(()=>{if(contributionMode!=="loading"&&preferences.recapSeen!==period&&!dialog.current?.open){dialog.current?.showModal();captureSafeEvent("recap_viewed")}},[contributionMode,period,preferences.recapSeen]);
 function finish(){update({recapSeen:period});if(contributionMode==="server")void fetch("/api/recap-preferences",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({latestSeenPeriod:period})});dialog.current?.close();setStep(0)}
 return <dialog ref={dialog} className="recap-dialog" aria-label={`${formatMonth(period)} recap`} onClose={()=>update({recapSeen:period})}><button className="recap-close" onClick={finish} aria-label="Close recap">×</button><div className="recap-step">{step+1} of {slides.length}</div><div aria-live="polite">{slides[step]}</div><div className="recap-modal-actions"><button className="button secondary" onClick={finish}>Close</button>{step>0&&<button className="button secondary" onClick={()=>setStep(value=>value-1)}>Back</button>}{step<slides.length-1?<button className="button lime" onClick={()=>setStep(value=>value+1)}>Next <ArrowRight size={17}/></button>:<button className="button lime" onClick={finish}>Done</button>}</div></dialog>}
