"use client";
import { useState } from "react";
import { useDemo } from "./demo-provider";
import { GraduationCap, Trophy, Search } from "lucide-react";
const profiles = [
  { name: "Alex Chen", college: "Stanford", strategy: "Growth", result: 18.4, bio: "Exploring long-term business growth and learning to evaluate company fundamentals." },
  { name: "Sarah Kim", college: "MIT", strategy: "Index", result: 16.2, bio: "Keeping things broad, simple and consistent with diversified index funds." },
  { name: "Mike Johnson", college: "Berkeley", strategy: "Dividend", result: 14.8, bio: "Studying cash flow, dividend sustainability and the power of reinvestment." },
  { name: "Emma Davis", college: "UCLA", strategy: "Index", result: 11.9, bio: "Learning how allocation and patience shape a long-term portfolio." },
  { name: "James Wilson", college: "USC", strategy: "Scalp", result: 10.5, bio: "Studying short-term price movements in simulation. Frequent trading brings substantial risk and costs." },
  { name: "Lisa Martinez", college: "UCSD", strategy: "Dividend", result: 9.8, bio: "Looking beyond yield to understand business quality and financial resilience." }
];
export function SocialLeaderboard() {
  const [query, setQuery] = useState("");
  const {preferences,update,announce}=useDemo();
  const [view,setView]=useState("Everyone");
  const [strategy, setStrategy] = useState("All strategies");
  const shown = profiles.filter(p=>(view === "Everyone" || preferences.follows.includes(p.name)) && (strategy === "All strategies" || p.strategy === strategy) && `${p.name} ${p.college}`.toLowerCase().includes(query.toLowerCase()));
  return <div className="workspace social-workspace"><section className="campus-banner"><GraduationCap size={32} aria-hidden="true"/><div><p className="eyebrow">Built around your campus</p><h2>Meet your investing crowd.</h2><p>Different colleges. Different approaches. Learn from each other.</p></div><span className="badge">Demo community</span></section>
    <div className="section-heading discover-research"><div><p className="eyebrow">Campus perspectives</p><h2><Trophy size={22} aria-hidden="true"/> Student leaderboard</h2></div><span>Sample season</span></div><p className="muted small">Fictional profiles · Ranked by illustrative season return, highest first. Returns are simulated and do not measure skill or predict future performance.</p>
    <div className="demo-toolbar"><div className="demo-tabs" role="group" aria-label="Community view">{["Everyone","Following"].map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{v}{v==="Following"?` (${preferences.follows.length})`:""}</button>)}</div><span className="demo-muted">Your campus: {preferences.college}</span></div><div className="social-filters"><label className="searchbox"><Search size={18} aria-hidden="true"/><span className="sr-only">Search name or college</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a name or college"/></label><label><span className="sr-only">Filter by investment strategy</span><select value={strategy} onChange={e=>setStrategy(e.target.value)}>{["All strategies", "Growth", "Dividend", "Index", "Scalp"].map(s=><option key={s}>{s}</option>)}</select></label></div>
    <p className="muted small" role="status">{shown.length} sample {shown.length === 1 ? "profile" : "profiles"}</p><div className="leaderboard"><div className="leaderboard-labels" aria-hidden="true"><span>Rank</span><span>Student / college</span><span>Strategy</span><span>Simulated return</span></div>{shown.map(p=><details className="student-profile" key={p.name}><summary><span className="student-rank">{String(profiles.indexOf(p)+1).padStart(2,"0")}</span><span className="student-identity"><span className="student-avatar" aria-hidden="true">{p.name.split(" ").map(n=>n[0]).join("")}</span><span><strong>{p.name}</strong><small>{p.college}</small></span></span><span className="strategy-tag">{p.strategy}</span><span className="student-return">+{p.result.toFixed(1)}%<small>View profile +</small></span></summary><div className="student-bio"><p className="eyebrow">Their approach</p><p>{p.bio}</p><div className="student-follow"><span className="muted small">Fictional profile · Following stays in your browser</span><button className="button secondary" aria-pressed={preferences.follows.includes(p.name)} onClick={()=>{const following=preferences.follows.includes(p.name);update({follows:following?preferences.follows.filter(n=>n!==p.name):[...preferences.follows,p.name]});announce(following?`Unfollowed ${p.name} in your demo.`:`Following ${p.name}. Find them in the Following tab.`);}}>{preferences.follows.includes(p.name)?"Following ✓":"Follow student"}</button></div></div></details>)}{!shown.length&&<div className="card"><h3>No students match yet</h3><p>Try another college or strategy, or explore Everyone to follow a student.</p><button className="button secondary" onClick={()=>{setQuery("");setStrategy("All strategies");setView("Everyone");}}>Clear filters</button></div>}</div><p className="preview-note">Community preview. Profiles and returns are fictional. Following is saved only in this browser; no student is notified.</p></div>;
}
