import { z } from "zod";
import type { Holding } from "./domain";
const amount=z.preprocess(value=>typeof value==="string"&&value.trim()===""?undefined:value,z.coerce.number().finite().nonnegative().max(1e12));
const rowSchema=z.object({symbol:z.string().trim().regex(/^[A-Za-z0-9.^=-]{1,12}$/),name:z.string().trim().min(1).max(160),quantity:amount,price:amount,previousClose:amount.optional(),costBasis:amount.optional(),sector:z.string().trim().max(80).default("Unclassified"),assetClass:z.enum(["equity","fund","fixed-income","cash"]).default("equity")});
function rows(input:string){const result:string[][]=[];let row:string[]=[];let cell="";let quoted=false;let closed=false;for(let i=0;i<input.length;i++){const c=input[i];if(quoted){if(c==='"'){if(input[i+1]==='"'){cell+='"';i++;}else{quoted=false;closed=true;}}else cell+=c;continue;}if(c==='"'){if(cell.trim()||closed)throw new Error("Invalid CSV quoting.");quoted=true;continue;}if(c===','||c==='\n'||c==='\r'){row.push(cell.trim());cell="";closed=false;if(c!==','){if(c==='\r'&&input[i+1]==='\n')i++;if(row.some(Boolean))result.push(row);row=[];}continue;}if(closed&&!/\s/.test(c))throw new Error("Invalid CSV quoting.");cell+=c;}if(quoted)throw new Error("A quoted field is missing its closing quote.");row.push(cell.trim());if(row.some(Boolean))result.push(row);return result;}
export function parseHoldingsCsv(input:string):Holding[]{
 if(new TextEncoder().encode(input).length>2_000_000)throw new Error("CSV is larger than 2 MB.");
 const lines=rows(input.replace(/^\uFEFF/,""));if(lines.length<2)throw new Error("CSV must include a header and at least one holding.");if(lines.length>5001)throw new Error("CSV can contain at most 5,000 holdings.");
 const headers=lines[0].map(h=>h.toLowerCase().replace(/[ _-]/g,""));if(new Set(headers).size!==headers.length)throw new Error("Duplicate column names are not supported.");for(const name of ["symbol","name","quantity","price"])if(!headers.includes(name))throw new Error(`Missing required column: ${name}`);
 const symbols=new Set<string>();
 return lines.slice(1).map((values,index)=>{if(values.length!==headers.length)throw new Error(`Invalid column count on row ${index+2}.`);const raw=Object.fromEntries(headers.map((h,i)=>[h,values[i]]));const parsed=rowSchema.safeParse({symbol:raw.symbol,name:raw.name,quantity:raw.quantity,price:raw.price,previousClose:raw.previousclose||undefined,costBasis:raw.costbasis||undefined,sector:raw.sector||undefined,assetClass:raw.assetclass||undefined});if(!parsed.success)throw new Error(`Invalid holding on row ${index+2}. Check the symbol, name and non-negative numbers.`);const symbol=parsed.data.symbol.toUpperCase();if(symbols.has(symbol))throw new Error(`Duplicate symbol on row ${index+2}. Combine each symbol into one row.`);symbols.add(symbol);return {...parsed.data,symbol,previousClose:parsed.data.previousClose??parsed.data.price};});
}
