import type { PortfolioSnapshot } from "./domain";
import { marketValue, summarizePortfolio } from "./portfolio";
export function demoAnswer(question:string,portfolio:PortfolioSnapshot){
 const q=question.toLowerCase();const summary=summarizePortfolio(portfolio);const dollars=(n:number)=>n.toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2});
 if(/\b(buy|sell|short|leverage|trade|scalp)\b/.test(q))return {text:"I can help you understand an investment, but this demo won’t tell you what to buy or sell. Start with what the investment holds, its costs and risks, and when you might need the money.\nA leaderboard result is not a reason to copy a trade. Try asking ‘How do I spread my risk?’",href:"/learn/research-checklist",label:"Open the research checklist"};
 if(/divers|risk|concentrat|mix|balance|overlap/.test(q)){const largest=summary.allocations[0];return {text:`${largest?`${largest.symbol} is ${largest.percent.toFixed(1)}% of this portfolio. `:""}A big position has more influence on the total. If it’s a fund, look at the investments inside before judging how concentrated it is.\nSpreading investments across companies, industries and countries can reduce reliance on one area. Different funds can overlap, and a wider mix cannot prevent all losses.`,href:"/learn/spread-your-risk",label:"Learn about spreading risk"};}
 if(/fee|compound|growth|interest|saving|time/.test(q))return {text:"Compounding means money left invested can earn returns on earlier returns. Ongoing fees reduce the amount that stays invested, and their impact can build over time.\nTry the lesson calculator with different monthly contributions, years and fees. It uses a constant hypothetical return; it isn’t a forecast and excludes taxes and inflation.",href:"/learn/fees-and-time",label:"Try the growth calculator"};
 if(/etf|fund|bond/.test(q))return {text:"An ETF is a basket of investments that trades on an exchange. It may hold stocks, bonds or other assets. Some funds spread across many markets; others focus on one narrow area.\nA bond is a loan to an issuer. Bonds and bond funds have risks too, including changes in interest rates and the possibility an issuer cannot pay. Read the fund documents to understand the basket.",href:"/learn/what-you-own",label:"Stocks, bonds and funds explained"};
 const words=new Set(question.toUpperCase().match(/[A-Z0-9.^=-]+/g)??[]);const holding=portfolio.holdings.find(h=>words.has(h.symbol));
 if(holding){const value=marketValue(holding);const share=summary.totalValue?value/summary.totalValue*100:0;const change=holding.quantity*(holding.price-holding.previousClose);return {text:`${holding.symbol} — ${holding.name}. You have ${holding.quantity} shares at ${dollars(holding.price)} each in this ${portfolio.source==="csv"?"CSV preview":"sample portfolio"}. That is ${dollars(value)}, or ${share.toFixed(1)}% of the portfolio.\nIts contribution since the supplied previous close is ${change>=0?"+":"−"}${dollars(Math.abs(change))}. Those numbers explain the change, not its cause. I don’t have live news to verify why the price moved.`,href:`/discover?q=${encodeURIComponent(holding.symbol)}`,label:`Research ${holding.symbol}`};}
 if(/today|move|change|down|up|portfolio|holdings/.test(q))return {text:`This ${portfolio.source==="csv"?"CSV preview":"sample portfolio"} is worth ${dollars(summary.totalValue)} across ${portfolio.holdings.length} holdings. Its change from the supplied previous close is ${summary.dayChange>=0?"+":"−"}${dollars(Math.abs(summary.dayChange))} (${summary.dayChangePercent.toFixed(2)}%).\nThe calculation uses share quantities and prices from the current workspace. No live market feed or news explanation is connected. A price move alone does not tell you what to do next.`,href:"/portfolio",label:"Explore the portfolio breakdown"};
 if(/earnings|revenue|profit|research|checklist/.test(q))return {text:"Start with three questions: are sales growing, is the business keeping more profit, and is cash flow supporting that profit? Compare periods and read the original filing for context.\nThen ask how the investment fits your current holdings, time horizon and costs. Popularity and a single headline aren’t enough to judge an investment.",href:"/learn/read-earnings",label:"Learn to read beyond the headline"};
 return {text:"This demo guide covers your holdings, portfolio changes, ETFs, risk, fees and research basics. It uses curated explanations and local portfolio math, not a live AI model.\nTry ‘Explain my portfolio’, ‘What is an ETF?’ or ask about a ticker you own. For a topic outside this demo, start with the learning library and its original sources.",href:"/learn",label:"Explore the learning library"};
}
