export const lessons = [
  { id:"what-you-own",title:"What do you actually own?",tag:"Start here",minutes:3,color:"green",intro:"A stock, a bond and a fund walk into your portfolio. Here’s what each one does.",sections:[
    {title:"Stocks: a small piece of a business",body:"A share gives you an ownership stake in a company. Its price can rise or fall, and some companies pay dividends. Neither a rising price nor a dividend is guaranteed."},
    {title:"Bonds: a loan, with risks",body:"When you buy a bond, you lend money to an issuer, such as a company or government. It promises payments under the bond’s terms. Issuers can fail to pay, and bond prices can fall as interest rates change."},
    {title:"Funds: a basket in one purchase",body:"A fund pools investments. An ETF trades on an exchange and may hold many stocks or bonds. Read what is inside: one fund might cover thousands of businesses, while another concentrates on one industry."}
  ],takeaway:"The ticker is a label. The holdings inside tell you what you own.",question:"Which statement about an ETF is true?",options:["It always holds every company in the world.","It can hold a basket of stocks or bonds.","Its value cannot fall."],correct:1,explanation:"ETFs can hold a basket of investments, but the basket and its risks differ from fund to fund.",source:"https://www.investor.gov/introduction-investing/investing-basics/investment-products/mutual-funds-and-exchange-traded-2",sourceLabel:"Investor.gov · ETFs"},
  { id:"why-prices-move",title:"Why did the price move?",tag:"Make sense of markets",minutes:3,color:"purple",intro:"A red day is a change in price. It is not automatically a change in your plan.",sections:[
    {title:"Prices reflect expectations",body:"A share price reflects what buyers and sellers are willing to accept. News about profits, interest rates or the economy can change those expectations. The same news can affect different businesses differently."},
    {title:"A good company can have a bad day",body:"A stock can fall even after profits grow if investors expected more. One day’s move does not tell you whether a business has improved or worsened over the long run."},
    {title:"Ask before you react",body:"What changed? Is there an original source? Does the news affect the business or just today’s mood? Compare the answers with why you held the investment, your time horizon and the risks you can afford."}
  ],takeaway:"Price is information, not an instruction.",question:"A stock falls today. What can you conclude from that alone?",options:["The price fell; you need more context.","The business will fail.","It must rise tomorrow."],correct:0,explanation:"A price change alone cannot explain the cause or predict what happens next.",source:"https://www.investor.gov/introduction-investing/investing-basics/investment-products/stocks",sourceLabel:"Investor.gov · Stocks"},
  { id:"spread-your-risk",title:"Don’t put it all in one basket.",tag:"Build your mix",minutes:3,color:"gold",intro:"Owning ten tickers doesn’t help much if they all depend on the same thing.",sections:[
    {title:"Different names can hide the same risk",body:"A technology stock and a technology fund might both depend on the same large companies. A longer holdings list is not proof of a wider mix."},
    {title:"Look across the whole portfolio",body:"Consider the companies, industries, countries and investment types you own. Funds can help spread investments, but narrow funds may still leave you concentrated in one area."},
    {title:"More variety is not a safety guarantee",body:"Spreading investments can reduce reliance on a single company or market. It cannot prevent all losses, especially when many markets fall together. Your mix should also fit when you need the money."}
  ],takeaway:"Count the different risks, not just the different tickers.",question:"Which pair is most likely to overlap?",options:["Two funds tracking the same U.S. stock index.","A cash account and a single company stock.","A government bond and a technology stock."],correct:0,explanation:"Funds tracking the same index tend to hold many of the same investments.",source:"https://www.investor.gov/introduction-investing/getting-started/asset-allocation",sourceLabel:"Investor.gov · Diversification"},
  { id:"read-earnings",title:"Read past the headline.",tag:"Research basics",minutes:3,color:"blue",intro:"You don’t need to decode every line. Start with three useful questions.",sections:[
    {title:"Is the business selling more?",body:"Revenue is money earned from sales before expenses. Compare it with the same period last year and read management’s explanation. A one-time event can make a single quarter misleading."},
    {title:"Is it keeping more?",body:"Profit is what remains after the relevant expenses. Revenue can rise while profit falls. Check whether costs, interest or unusual charges explain the difference."},
    {title:"Is cash following profit?",body:"Accounting profit and cash flow are different. Read the cash flow statement, debt disclosures and risk factors. Use the company’s original filings; a social post or one ratio is not the whole story."}
  ],takeaway:"Sales, profit, cash. Then ask what changed and why.",question:"Sales rose but profit fell. What is a useful next question?",options:["Can I ignore the expenses?","Did costs or unusual charges grow faster than sales?","Does this guarantee next quarter will improve?"],correct:1,explanation:"The gap between sales and profit is a reason to investigate expenses and context.",source:"https://www.investor.gov/introduction-investing",sourceLabel:"Investor.gov · Research before investing"},
  { id:"fees-and-time",title:"Small amounts. Long game.",tag:"Try the calculator",minutes:4,color:"purple",intro:"Time and costs can make a big difference. Move the sliders and see for yourself.",sections:[
    {title:"Growth can build on growth",body:"Compounding means returns can earn returns when they remain invested. It works over time, but real investment returns vary and can be negative."},
    {title:"Fees compound too",body:"Ongoing fees reduce the money that remains invested. Two investments with the same return before fees can end at different values after costs. Always read the fee details."},
    {title:"A model is not a forecast",body:"The calculator below assumes a constant return, monthly growth and contributions at each month’s end. It excludes taxes and inflation. Real markets do not follow a smooth curve."}
  ],takeaway:"Keep an eye on costs. Give your plan time. Don’t mistake an example for a promise.",question:"Why do ongoing fees matter over a long period?",options:["They guarantee higher returns.","They only affect the first year.","They reduce money that can keep growing."],correct:2,explanation:"Fees can reduce both the balance and future growth on that balance.",source:"https://www.investor.gov/introduction-investing/general-resources/news-alerts/alerts-bulletins/investor-bulletins/updated",sourceLabel:"Investor.gov · Fees and expenses"},
  { id:"research-checklist",title:"Your before-you-invest checklist.",tag:"Put it together",minutes:3,color:"green",intro:"Build a repeatable process you can explain in your own words.",sections:[
    {title:"Know what it is",body:"Can you explain the investment and how it might make or lose money? Find the original company filing or fund documents. If the explanation is unclear, that is a reason to keep researching."},
    {title:"Know where it fits",body:"What does it add to your existing mix? What fees would you pay? When might you need the money? Write down a realistic downside, not just the hoped-for gain."},
    {title:"Know your source",body:"A popular post is not verification. Check the author’s incentives, dates and primary sources. Be skeptical of guaranteed returns or pressure to act now."}
  ],takeaway:"Understand it. Check it. Explain where it fits.",question:"Which research source is the best starting point for a fund’s fees?",options:["An anonymous comment.","The fund’s official documents.","Its most-liked social post."],correct:1,explanation:"Official fund documents disclose costs and objectives. Popularity does not replace verification.",source:"https://www.investor.gov/introduction-investing",sourceLabel:"Investor.gov · Investing basics"}
] as const;
