import { NextResponse } from "next/server";
import { z } from "zod";
import { getAuthenticatedUser } from "@/lib/supabase/server";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";
import { env,integrations } from "@/lib/env";
import { sha256 } from "@/lib/crypto";
import { sendRecapEmail } from "@/lib/providers/resend";
import { createRecapToken } from "@/lib/server/recap-tokens";
const schema=z.object({email:z.string().email().max(254)});
export async function POST(request:Request){const user=await getAuthenticatedUser(),admin=createSupabaseAdminClient();if(!user)return NextResponse.json({reason:"Sign in before verifying a campus."},{status:401});if(!admin||!integrations.resend)return NextResponse.json({reason:"Campus verification is not configured."},{status:503});const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({reason:"Enter a valid school email."},{status:400});const email=parsed.data.email.trim().toLowerCase(),domain=email.split("@")[1];const allowlist=new Set((env.CAMPUS_DOMAIN_ALLOWLIST||"").split(",").map(item=>item.trim().toLowerCase()).filter(Boolean));if(!domain.endsWith(".edu")&&!allowlist.has(domain))return NextResponse.json({reason:"Use a verified school domain."},{status:400});const exp=Math.floor(Date.now()/1000)+30*60;const token=createRecapToken({purpose:"campus",userId:user.id,domain,exp}),tokenHash=sha256(token);const {error}=await admin.from("campus_verification_challenges").insert({user_id:user.id,email_hash:sha256(email),campus_domain:domain,token_hash:tokenHash,expires_at:new Date(exp*1000).toISOString()});if(error)return NextResponse.json({reason:"Verification could not be started."},{status:500});const origin=env.APP_URL||new URL(request.url).origin;const link=origin+"/api/campus/confirm?token="+encodeURIComponent(token);await sendRecapEmail({to:email,subject:"Verify your campus for Cornerstone",html:"<p>Verify your school email for Cornerstone.</p><p><a href=\""+link+"\">Verify campus</a></p><p>This link expires in 30 minutes. You choose separately whether to join an anonymous consistency cohort.</p>",idempotencyKey:"campus-"+tokenHash});return NextResponse.json({sent:true,message:"Check your school email. The link expires in 30 minutes."})}
