import { ImageResponse } from "next/og";
import { createSupabaseServerClient, getAuthenticatedUser } from "@/lib/supabase/server";
import { sampleContributions } from "@/lib/sample-contributions";
import { formatMonth, monthKeyInTimeZone, shiftMonth, summarizeRecap, type ContributionEvent } from "@/lib/recap";
import { hasProEntitlement } from "@/lib/billing";
export const runtime="nodejs";
const size={width:1200,height:630};
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){
 const {id}=await params;const url=new URL(request.url);const visible=url.searchParams.get("amounts")==="shown";let period=url.searchParams.get("period")||"2026-09";let contributed=0,streak=0;
 if(id==="sample"){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(period))return Response.json({reason:"Invalid recap period."},{status:400});const summary=summarizeRecap(sampleContributions,period);contributed=summary.contributed;streak=summary.streak;}
 else {const user=await getAuthenticatedUser();const client=await createSupabaseServerClient();if(!user||!client)return Response.json({reason:"Sign in to download this recap."},{status:401});if(id==="current"){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(period))return Response.json({reason:"Invalid recap period."},{status:400});const [{data,error},{data:entitlement},{data:preference}]=await Promise.all([client.from("contribution_events").select("id,occurred_on,amount,currency,direction,source,status").eq("user_id",user.id).neq("status","deleted"),client.from("subscription_entitlements").select("status,current_period_end").eq("user_id",user.id).maybeSingle(),client.from("recap_preferences").select("timezone").eq("user_id",user.id).maybeSingle()]);if(error)return Response.json({reason:"Recap not found."},{status:404});const events:ContributionEvent[]=(data??[]).map(row=>({id:String(row.id),occurredOn:String(row.occurred_on),amount:Number(row.amount),currency:"USD",kind:row.direction as ContributionEvent["kind"],source:row.source as ContributionEvent["source"],status:row.status as ContributionEvent["status"]}));const latest=monthKeyInTimeZone(new Date(),preference?.timezone||"America/Chicago"),freePeriods=[latest,shiftMonth(latest,-1),shiftMonth(latest,-2)];if(!hasProEntitlement(entitlement?.status,entitlement?.current_period_end)&&!freePeriods.includes(period))return Response.json({reason:"Full recap history is available with Pro."},{status:403});const summary=summarizeRecap(events,period);contributed=summary.contributed;streak=summary.streak;}else{const [{data,error},{data:entitlement},{data:preference}]=await Promise.all([client.from("recap_snapshots").select("period_start,period_kind,contributed,streak").eq("id",id).eq("user_id",user.id).maybeSingle(),client.from("subscription_entitlements").select("status,current_period_end").eq("user_id",user.id).maybeSingle(),client.from("recap_preferences").select("timezone").eq("user_id",user.id).maybeSingle()]);if(error||!data)return Response.json({reason:"Recap not found."},{status:404});period=String(data.period_start).slice(0,7);const latest=monthKeyInTimeZone(new Date(),preference?.timezone||"America/Chicago"),freePeriods=[latest,shiftMonth(latest,-1),shiftMonth(latest,-2)];if(!hasProEntitlement(entitlement?.status,entitlement?.current_period_end)&&(data.period_kind!=="monthly"||!freePeriods.includes(period)))return Response.json({reason:"Full recap history is available with Pro."},{status:403});contributed=Number(data.contributed);streak=Number(data.streak);}}
 const amount=contributed.toLocaleString("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});
 return new ImageResponse(<div style={{width:"100%",height:"100%",display:"flex",flexDirection:"column",padding:"64px",color:"white",background:"linear-gradient(140deg,#173f2f,#0d2c21)",fontFamily:"Arial, sans-serif"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontFamily:"Georgia, serif",fontSize:34}}>Cornerstone<span style={{color:"#d6f58d"}}>.</span></span><span style={{fontSize:19,color:"#bcd0c1",letterSpacing:2}}>MY RECAP</span></div><div style={{display:"flex",flexDirection:"column",marginTop:72}}><span style={{fontSize:22,color:"#bfd2c3",letterSpacing:2,textTransform:"uppercase"}}>{formatMonth(period)}</span><strong style={{fontSize:122,letterSpacing:-8,lineHeight:1,marginTop:12}}>{visible?amount:"••••"}</strong><span style={{fontSize:51,fontWeight:700,letterSpacing:-2,marginTop:18}}>I added to my future.</span></div><div style={{display:"flex",gap:18,marginTop:"auto"}}><span style={{padding:"12px 20px",border:"1px solid #ffffff38",borderRadius:40,fontSize:21}}>{streak} month streak</span><span style={{padding:"12px 20px",border:"1px solid #ffffff38",borderRadius:40,fontSize:21}}>Personal progress</span></div></div>,{...size,headers:{"Content-Disposition":`attachment; filename="cornerstone-${period}.png"`,"Cache-Control":"private, no-store","X-Content-Type-Options":"nosniff"}})
}
